# Generated by Django 5.2.7 on 2025-10-09 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='creation_date',
            new_name='created_at',
        ),
    ]
